### ISSUE TITLE
ValueError: 409 {u'error': {u'message': u'There is a conflict with the given data.', u'type': u'conflict', u'revision_conflict': True, u'translation_key': u'api_error_conflict'}}

### ISSUE THREAD

**Issue by rogerillu** [mieubrisse/wunderpy2#9]
It was working like a charm but today to delete an item and it gives this error. To add an item it works correctly, and to list them too.

--------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "menudinar.py", line 126, in <module>
    deleteWunder()
  File "menudinar.py", line 99, in deleteWunder
    client.delete_task(task['id'],1)
  File "/usr/local/lib/python2.7/dist-packages/wunderpy2/wunderclient.py", line 89, in delete_task
    tasks_endpoint.delete_task(self, task_id, revision)
  File "/usr/local/lib/python2.7/dist-packages/wunderpy2/tasks_endpoint.py", line 91, in delete_task
    client.authenticated_request(endpoint, 'DELETE', params=params)
  File "/usr/local/lib/python2.7/dist-packages/wunderpy2/wunderclient.py", line 45, in authenticated_request
    return self.api.request(endpoint, method=method, headers=headers, params=params, data=data)
  File "/usr/local/lib/python2.7/dist-packages/wunderpy2/wunderapi.py", line 76, in request
    self._validate_response(method, response)
  File "/usr/local/lib/python2.7/dist-packages/wunderpy2/wunderapi.py", line 40, in _validate_response
    raise ValueError('{} {}'.format(response.status_code, str(response.json())))
ValueError: 409 {u'error': {u'message': u'There is a conflict with the given data.', u'type': u'conflict', u'revision_conflict': True, u'translation_key': u'api_error_conflict'}}
----------------------------------------------------------------------------------------------------------------------------------

It seems to be an authentication error?

The command I am sending is: client.delete_task(task['id'],1)

Thanks!

Awesome app! :+1:

**Comment by mieubrisse** [comment]
Hey @rogerillu , glad you like wunderpy2! 

This looks like it's coming from a revision conflict - all Wunderlist objects (tasks, lists, etc.) have a server-side "revision" associated with them that serves as an indicator of what version they are. This helps keep them in sync across multiple Wunderlist-using devices using, because the server will reject any modifications to an object if the revision you pass in when modifying the object doesn't match the revision the server has stored for it.

Here, you're trying to delete a task with some ID, passing in revision `1`, but the server's rejecting it because the server's copy of the task has a revision > 1. To fix, you'll need to pass in the revision that you received from the server for that task to the `delete_task` call. If the task's updated frequently, make sure to call `get_task` again before you try the delete to ensure you have the latest revision.

Let me know if that helps!
mieubrisse

**Comment by mieubrisse** [comment]
Closing due to inactivity
